### ISSUE TITLE
Angular is Beta, so Formly development makes sense now

### ISSUE THREAD

**Issue by mohammedzamakhan** [formly-js/angular2-formly#2]
I would love to see formly development to start as we have angular2 in beta, lets start this work, I would love to contribute to the project

**Comment by drbourbon** [comment]
+1

**Comment by divyakumarjain** [comment]
+1

**Comment by brutalcrozt** [comment]
@tilmanpotthof what do you think?

**Comment by renkema79** [comment]
+1

**Comment by barkoczi** [comment]
I would like to contribute to the project, let me know the details.

**Comment by brutalcrozt** [comment]
@barkoczi at this time [we need maintainer](https://github.com/formly-js/angular-formly/issues/638)

**Comment by tb** [comment]
https://angular.io/docs/ts/latest/cookbook/dynamic-form.html

**Comment by akeller** [comment]
Angular2 has a ton of built in support for data driven and template driven form building including a [formBuilder ](https://angular.io/docs/js/latest/api/common/FormBuilder-class.html). I would challenge that formly's concepts are mostly addressed in the core of the framework.

**Comment by mohammedzamakhan** [comment]
@akeller Angular2 has really good data driven and template driven form building for sure, but it does not have something that makes form building easier for business application. By using Formly you can develop complex forms, without writing a line of html template. Basically what I mean is, we have to make the model driven forms from Angular 2 to much easier form, please look at Angular 1's http://angular-formly.com/ ,and look at all the example and support for business application.

**Comment by mohammedzamakhan** [comment]
Closing this issue, since I have started working on it
